### ISSUE TITLE
Bullets and numbered layout 👍🏻 

### ISSUE THREAD

**Issue by hkaur008** [hkaur008/GitMarkonics#25]
Method to add bullets and number list in readme format !

**Comment by RiyaGupta89** [comment]
Please describe a bit more about this issue? And can I work under this issue please?

**Comment by varunwho** [comment]
@hkaur008 can you explain this issue please

**Comment by ishitakapoor26** [comment]
@hkaur008 pls assign me this issue.

**Comment by varshitha1707** [comment]
> Method to add bullets and number list in readme format !

I have figured out how to add a method for making bullets and numbered lists in the readme format.
I have linked it to a button beside the bold and italic buttons.

Please Assign me this issue under **LGMSOC21** 

I can immediately raise a pull request and get it merged.
ThankYou.

**Comment by hkaur008** [comment]
> > Method to add bullets and number list in readme format !
> 
> I have figured out how to add a method for making bullets and numbered lists in the readme format.
> I have linked it to a button beside the bold and italic buttons.
> 
> something like this:
> ![image](https://user-images.githubusercontent.com/69676094/123104978-09673700-d455-11eb-90ec-bd692e64370c.png)
> 
> Please Assign me this issue under **LGMSOC21**
> 
> I can immediately raise a pull request and get it merged.
> ThankYou.
> 
> @hkaur008 @DhruvSingla007 Please Check.
Can you make pulll request ?

**Comment by varshitha1707** [comment]
Can You please assign it to me under LGMSOC21 @hkaur008 ?
