### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by kumarishalini6** [hkaur008/GitMarkonics#63]
**Describe the bug**
No navbar available in login and register page if a person want to go back to the home page there should be navbar so that by clicking on home button they redirect on homepage.\
 
**To Reproduce**
1. Go to 'project'
2. Click on 'register page'
3. See error
4. Add navbar in both login and register page

**Comment by kumarishalini6** [comment]
@yajushiSri please assign this issue to me

**Comment by hkaur008** [comment]
do you still want to take up this issue?

**Comment by kumarishalini6** [comment]
Yes

**Comment by kumarishalini6** [comment]
Can you please assign me

**Comment by 7JKaushal** [comment]
I would love to contribute to this if it's still open!

**Comment by Garima-7** [comment]
assign this to me
